
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.HBox hbox3;
	private global::Gtk.VBox vbox8;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Entry ingresar;
	private global::Gtk.Button convertir;
	private global::Gtk.VBox vbox10;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label4;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry valordolar;
	private global::Gtk.Entry dolaresC;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label6;
	private global::Gtk.Entry valorpeso;
	private global::Gtk.Entry pesosC;
	private global::Gtk.VBox vbox11;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label label7;
	private global::Gtk.Entry valorlibra;
	private global::Gtk.Entry librasC;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Label label8;
	private global::Gtk.Entry valoryen;
	private global::Gtk.Entry yenesC;
	private global::Gtk.VBox vbox12;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label label9;
	private global::Gtk.Entry valorrublo;
	private global::Gtk.Entry rublosC;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label10;
	private global::Gtk.Entry valorcorona;
	private global::Gtk.Entry coronasC;
	private global::Gtk.HBox hbox12;
	private global::Gtk.VBox vbox13;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label label12;
	private global::Gtk.Entry valorreal;
	private global::Gtk.Entry realesC;
	private global::Gtk.HBox hbox14;
	private global::Gtk.Label label13;
	private global::Gtk.Entry valorrupia;
	private global::Gtk.Entry rupiasC;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("CONVERSOR DE MONEDA");
		this.label2.Justify = ((global::Gtk.Justification)(2));
		this.label2.Ellipsize = ((global::Pango.EllipsizeMode)(1));
		this.vbox1.Add (this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("INTRODUCE LA CANTIDAD DE EUROS A CONVERTIR");
		this.vbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.ingresar = new global::Gtk.Entry ();
		this.ingresar.CanFocus = true;
		this.ingresar.Name = "ingresar";
		this.ingresar.IsEditable = true;
		this.ingresar.InvisibleChar = '•';
		this.hbox5.Add (this.ingresar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.ingresar]));
		w3.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.convertir = new global::Gtk.Button ();
		this.convertir.CanFocus = true;
		this.convertir.Name = "convertir";
		this.convertir.UseUnderline = true;
		this.convertir.Label = global::Mono.Unix.Catalog.GetString ("CONVERTIR");
		this.hbox5.Add (this.convertir);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.convertir]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox8.Add (this.hbox5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox5]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox10.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hseparator1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("DOLARES");
		this.hbox6.Add (this.label4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label4]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.valordolar = new global::Gtk.Entry ();
		this.valordolar.CanFocus = true;
		this.valordolar.Name = "valordolar";
		this.valordolar.Text = global::Mono.Unix.Catalog.GetString ("0.898174012");
		this.valordolar.IsEditable = false;
		this.valordolar.WidthChars = 11;
		this.valordolar.InvisibleChar = '•';
		this.hbox1.Add (this.valordolar);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.valordolar]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox6.Add (this.hbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hbox1]));
		w9.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.dolaresC = new global::Gtk.Entry ();
		this.dolaresC.CanFocus = true;
		this.dolaresC.Name = "dolaresC";
		this.dolaresC.IsEditable = false;
		this.dolaresC.InvisibleChar = '•';
		this.hbox6.Add (this.dolaresC);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.dolaresC]));
		w10.Position = 2;
		this.vbox10.Add (this.hbox6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox6]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("PESOS");
		this.hbox7.Add (this.label6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label6]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.valorpeso = new global::Gtk.Entry ();
		this.valorpeso.WidthRequest = 105;
		this.valorpeso.HeightRequest = 0;
		this.valorpeso.CanFocus = true;
		this.valorpeso.Name = "valorpeso";
		this.valorpeso.Text = global::Mono.Unix.Catalog.GetString ("0.047341854");
		this.valorpeso.IsEditable = false;
		this.valorpeso.InvisibleChar = '•';
		this.hbox7.Add (this.valorpeso);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.valorpeso]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.pesosC = new global::Gtk.Entry ();
		this.pesosC.CanFocus = true;
		this.pesosC.Name = "pesosC";
		this.pesosC.IsEditable = false;
		this.pesosC.InvisibleChar = '•';
		this.hbox7.Add (this.pesosC);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.pesosC]));
		w14.Position = 2;
		w14.Expand = false;
		this.vbox10.Add (this.hbox7);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox7]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox8.Add (this.vbox10);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox10]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("LIBRAS");
		this.hbox8.Add (this.label7);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label7]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.valorlibra = new global::Gtk.Entry ();
		this.valorlibra.CanFocus = true;
		this.valorlibra.Name = "valorlibra";
		this.valorlibra.Text = global::Mono.Unix.Catalog.GetString ("1.16333294");
		this.valorlibra.IsEditable = false;
		this.valorlibra.InvisibleChar = '•';
		this.hbox8.Add (this.valorlibra);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.valorlibra]));
		w18.Position = 1;
		// Container child hbox8.Gtk.Box+BoxChild
		this.librasC = new global::Gtk.Entry ();
		this.librasC.CanFocus = true;
		this.librasC.Name = "librasC";
		this.librasC.IsEditable = false;
		this.librasC.InvisibleChar = '•';
		this.hbox8.Add (this.librasC);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.librasC]));
		w19.Position = 2;
		this.vbox11.Add (this.hbox8);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox8]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("YENES");
		this.hbox9.Add (this.label8);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label8]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.valoryen = new global::Gtk.Entry ();
		this.valoryen.CanFocus = true;
		this.valoryen.Name = "valoryen";
		this.valoryen.Text = global::Mono.Unix.Catalog.GetString ("125.23");
		this.valoryen.IsEditable = false;
		this.valoryen.InvisibleChar = '•';
		this.hbox9.Add (this.valoryen);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.valoryen]));
		w22.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.yenesC = new global::Gtk.Entry ();
		this.yenesC.CanFocus = true;
		this.yenesC.Name = "yenesC";
		this.yenesC.IsEditable = false;
		this.yenesC.InvisibleChar = '•';
		this.hbox9.Add (this.yenesC);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.yenesC]));
		w23.Position = 2;
		this.vbox11.Add (this.hbox9);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox9]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("RUBLOS");
		this.hbox10.Add (this.label9);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label9]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.valorrublo = new global::Gtk.Entry ();
		this.valorrublo.CanFocus = true;
		this.valorrublo.Name = "valorrublo";
		this.valorrublo.Text = global::Mono.Unix.Catalog.GetString ("0.01560");
		this.valorrublo.IsEditable = false;
		this.valorrublo.InvisibleChar = '•';
		this.hbox10.Add (this.valorrublo);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.valorrublo]));
		w26.Position = 1;
		// Container child hbox10.Gtk.Box+BoxChild
		this.rublosC = new global::Gtk.Entry ();
		this.rublosC.CanFocus = true;
		this.rublosC.Name = "rublosC";
		this.rublosC.IsEditable = false;
		this.rublosC.InvisibleChar = '•';
		this.hbox10.Add (this.rublosC);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.rublosC]));
		w27.Position = 2;
		this.vbox12.Add (this.hbox10);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox10]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("CORONAS");
		this.hbox11.Add (this.label10);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label10]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.valorcorona = new global::Gtk.Entry ();
		this.valorcorona.CanFocus = true;
		this.valorcorona.Name = "valorcorona";
		this.valorcorona.Text = global::Mono.Unix.Catalog.GetString ("0.10604");
		this.valorcorona.IsEditable = false;
		this.valorcorona.InvisibleChar = '•';
		this.hbox11.Add (this.valorcorona);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.valorcorona]));
		w30.Position = 1;
		// Container child hbox11.Gtk.Box+BoxChild
		this.coronasC = new global::Gtk.Entry ();
		this.coronasC.CanFocus = true;
		this.coronasC.Name = "coronasC";
		this.coronasC.IsEditable = false;
		this.coronasC.InvisibleChar = '•';
		this.hbox11.Add (this.coronasC);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.coronasC]));
		w31.Position = 2;
		this.vbox12.Add (this.hbox11);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox11]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("REALES");
		this.hbox13.Add (this.label12);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label12]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.valorreal = new global::Gtk.Entry ();
		this.valorreal.CanFocus = true;
		this.valorreal.Name = "valorreal";
		this.valorreal.Text = global::Mono.Unix.Catalog.GetString ("3.4947");
		this.valorreal.IsEditable = false;
		this.valorreal.InvisibleChar = '•';
		this.hbox13.Add (this.valorreal);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.valorreal]));
		w34.Position = 1;
		// Container child hbox13.Gtk.Box+BoxChild
		this.realesC = new global::Gtk.Entry ();
		this.realesC.CanFocus = true;
		this.realesC.Name = "realesC";
		this.realesC.IsEditable = false;
		this.realesC.InvisibleChar = '•';
		this.hbox13.Add (this.realesC);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.realesC]));
		w35.Position = 2;
		this.vbox13.Add (this.hbox13);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox13]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("RUPIAS");
		this.hbox14.Add (this.label13);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label13]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.valorrupia = new global::Gtk.Entry ();
		this.valorrupia.CanFocus = true;
		this.valorrupia.Name = "valorrupia";
		this.valorrupia.Text = global::Mono.Unix.Catalog.GetString ("71.17");
		this.valorrupia.IsEditable = false;
		this.valorrupia.InvisibleChar = '•';
		this.hbox14.Add (this.valorrupia);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.valorrupia]));
		w38.Position = 1;
		// Container child hbox14.Gtk.Box+BoxChild
		this.rupiasC = new global::Gtk.Entry ();
		this.rupiasC.CanFocus = true;
		this.rupiasC.Name = "rupiasC";
		this.rupiasC.IsEditable = false;
		this.rupiasC.InvisibleChar = '•';
		this.hbox14.Add (this.rupiasC);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.rupiasC]));
		w39.Position = 2;
		this.vbox13.Add (this.hbox14);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox14]));
		w40.Position = 1;
		w40.Expand = false;
		w40.Fill = false;
		this.hbox12.Add (this.vbox13);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vbox13]));
		w41.Position = 0;
		this.vbox12.Add (this.hbox12);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox12]));
		w42.Position = 2;
		w42.Expand = false;
		w42.Fill = false;
		this.vbox11.Add (this.vbox12);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox12]));
		w43.Position = 2;
		w43.Expand = false;
		w43.Fill = false;
		this.vbox8.Add (this.vbox11);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox11]));
		w44.Position = 2;
		w44.Expand = false;
		w44.Fill = false;
		this.hbox3.Add (this.vbox8);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox8]));
		w45.Position = 0;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 407;
		this.DefaultHeight = 361;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.convertir.Clicked += new global::System.EventHandler (this.OnConvertirClicked);
	}
}
